### ISSUE TITLE
url entrypoint

### ISSUE THREAD

**Issue by petoor** [lucalianas/ome_seadragon_compose#2]
Hi @lucalianas 

Thank you for this very well done compose file.

I'm trying to get this up and running and it seems to be building the containers correctly.
However, I cant access the seadragon web interface at localhost, localhost:8080 etc... after doing a docker-compose up.

What is the default url for the seadragon web?

**Comment by petoor** [comment]
So, if i go to localhost i simply get a 503 error and nginx cant find http://ome-seadragon.local 
What do i need to configure?

**Comment by lucalianas** [comment]
Hi @petoor 
the docker compose relies on **jwilder/nginx-proxy** to expose the nginx servers on port 80, this container then takes care of redirecting requests to the correct server according to the requested hostname.

The default host http://ome-seadragon.local can't be resolved by default, what you have to do is update your **/etc/hosts** file (in Linux or OSX systems) or the equivalent in Windows systems (which I don't know where to find, sorry) and add the following line

`
127.0.0.1  ome-seadragon.local
`

this way all the requests will be automatically redirected to your localhost network and the docker compose should be working fine.

Please, let me know if this fixes your problem.

**Comment by lucalianas** [comment]
BTW, I updated the docker compose to use the latest version of ome_seadragon

**Comment by petoor** [comment]
Thank you for updating the docker-compose file and thank you for the suggestion with adding the information to the /etc/hosts file.
Accessing http://ome-seadragon.local/ works now! :+1:  however localhost throws a 503.

Do you know if there is a way to also get localhost to work?

**Comment by petoor** [comment]
actually changing .local to .localhost in the docker-compose and in the config file works. 
I have ome-seadragon as a subdomain but that is fine for my usecase. 

Thank you for the help
